# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = docbook_dev_note
SUB_SRC_FILES = \
    preface.xml \
    ch01_build_env.xml \
    ch02_notes.xml \
    ch03_faq.xml \
    ch04_materials.xml \
    ch05_issues.xml \
    ch06_examples.xml \
    ch07_concept_knowledge.xml \
    appendix.xml \
    reference.xml

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk